version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          DATABASE_URL_TEST: "postgres://postgres@localhost:5432/population-m-s-test"
      
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: population-m-s-test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: INSTALL DEPENDENCIES
          command: yarn install

      - run:
          name: INSTALL PG CLIENT
          command: sudo apt install -y postgresql-client || true

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: TEST
          command: yarn test

      - run:
          name: UPLOAD COVERAGE
          command: yarn test:cov
